### ISSUE TITLE
Initial Docker Setup

### ISSUE THREAD

**Issue by Robzilla** [TheHive-Project/TheHiveDocs#189]
Hi all

Just trying to get a basic install up and running using docker. I have used the all in one yaml compose file (https://raw.githubusercontent.com/TheHive-Project/TheHive/master/docker/thehive/docker-compose.yml) but cortex won't load and gives the following error "Error: ElasticSearch cluster is unreachable".

**Comment by jbagwell3609** [comment]
Same issue from my build about a month ago. Tested and appeared to isolate the problem to adding the Cortex Key inside the yaml. Interim work around was to build TheHive4 from RPM and cortex using docker-compose yaml.

**Comment by anelshaer** [comment]
same for me as well, is there any working docker-compose.yaml example so we can start understanding the platform. 

```
version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - xpack.security.enabled=false
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:8080:9001"
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:80:9000"
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
    command: --no-config --cortex-port 8080
volumes:
  esdata01:
    driver: local
```


Cortex config

```
search.uri = "http://127.0.0.1:9200"
analyzer.urls = "https://download.thehive-project.org/analyzers.json"
play.http.secret.key="randomgenerated"
```

TheHive Config

```
search.uri = "http://127.0.0.1:9200"
play.http.secret.key="4jYk7W3EALGoswqYNsMtFvVvp3rbHbxJBPjGRzTaMbfJEABSC9oTS4Ljpejk2VGr"
```
